const fs = require('fs')
const path = require('path')

const SKILLS_DIR = path.join(__dirname, '..', 'skills')

// 纯内容翻译 - 只翻译正文，不翻译 frontmatter
function translate(content) {
  // 分离 frontmatter 和内容
  const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/)
  if (!match) {
    return translateBody(content)
  }

  const frontmatter = match[1]
  const body = match[2]
  return `---\n${frontmatter}\n---\n${translateBody(body)}`
}

function translateBody(body) {
  const translations = [
    // Agent Skills 格式
    ['When to Use', '何时使用'],
    ['Quick Start', '快速开始'],
    ['Quick Reference', '快速参考'],
    ['Usage Examples', '使用示例'],
    ['Basic Usage', '基本用法'],
    ['Advanced Usage', '高级用法'],
    ['Examples', '示例'],
    ['Usage', '使用方法'],
    ['Best Practices', '最佳实践'],
    ['Tips & Tricks', '技巧提示'],
    ['Troubleshooting', '故障排除'],
    ['FAQ', '常见问题'],
    ['Commands Reference', '命令参考'],
    ['Common Options', '常用选项'],
    ['Options and Flags', '选项和标志'],
    ['Parameters', '参数'],
    ['Arguments', '参数'],
    ['Flags', '标志'],
    ['Environment Variables', '环境变量'],
    ['Exit Codes', '退出码'],
    ['Prerequisites', '前置条件'],
    ['Requirements', '要求'],
    ['Installation', '安装'],
    ['Setup', '设置'],
    ['Configuration', '配置'],
    ['Description', '说明'],
    ['Overview', '概述'],
    ['Introduction', '简介'],
    ['Summary', '概要'],
    ['Features', '特性'],
    ['Syntax', '语法'],
    ['Notes', '备注'],
    ['Warnings', '警告'],
    ['Caveats', '注意事项'],
    ['Limitations', '限制'],
    ['Changelog', '更新日志'],
    ['License', '许可'],
    ['Credits', '致谢'],
    ['Related', '相关'],
    ['See Also', '另见'],

    // Git 版本控制
    ['Repository', '仓库'],
    ['repository', '仓库'],
    ['Remote', '远程'],
    ['remote', '远程'],
    ['Branch', '分支'],
    ['branch', '分支'],
    ['Branches', '分支'],
    ['Commit', '提交'],
    ['commit', '提交'],
    ['Commits', '提交'],
    ['Merge', '合并'],
    ['merge', '合并'],
    ['Merging', '合并中'],
    ['Rebase', '变基'],
    ['rebase', '变基'],
    ['Rebasing', '变基中'],
    ['Conflict', '冲突'],
    ['conflict', '冲突'],
    ['Conflicts', '冲突'],
    ['Conflict Resolution', '冲突解决'],
    ['Staging', '暂存'],
    ['Staged', '已暂存'],
    ['Unstaged', '未暂存'],
    ['HEAD', 'HEAD'],
    ['Pull', '拉取'],
    ['pull', '拉取'],
    ['Push', '推送'],
    ['push', '推送'],
    ['Fetch', '获取'],
    ['Clone', '克隆'],
    ['Checkout', '检出'],
    ['Reset', '重置'],
    ['Revert', '撤销'],
    ['Log', '日志'],
    ['Diff', '差异'],
    ['Status', '状态'],
    ['ignore', '忽略'],
    ['Submodule', '子模块'],
    ['submodule', '子模块'],
    ['Stash', '暂存'],
    ['stash', '暂存'],
    ['Tag', '标签'],
    ['tag', '标签'],
    ['Bisect', '二分查找'],
    ['blame', '追溯'],
    ['Reword', '修改提交信息'],
    ['Squash', '压缩'],
    ['Amend', '修改'],
    ['Cherry-pick', '摘取'],
    ['Reflog', '引用日志'],
    ['Worktree', '工作树'],

    // Docker
    ['Container', '容器'],
    ['container', '容器'],
    ['Containers', '容器'],
    ['Image', '镜像'],
    ['image', '镜像'],
    ['Images', '镜像'],
    ['Volume', '存储卷'],
    ['volume', '存储卷'],
    ['Volumes', '存储卷'],
    ['Network', '网络'],
    ['network', '网络'],
    ['Networks', '网络'],
    ['Dockerfile', 'Dockerfile'],
    ['Compose', 'Compose'],
    ['Compose stack', 'Compose 栈'],
    ['Registry', '镜像仓库'],
    ['Hub', '中心'],
    ['Layer', '层'],
    ['Build', '构建'],
    ['build', '构建'],
    ['Buildkit', 'Buildkit'],
    ['Multi-stage', '多阶段'],
    ['Run', '运行'],
    ['run', '运行'],
    ['Stop', '停止'],
    ['stop', '停止'],
    ['Restart', '重启'],
    ['Pause', '暂停'],
    ['Unpause', '恢复'],
    ['Kill', '终止'],
    ['Remove', '删除'],
    ['Prune', '清理'],
    ['Clean', '清理'],
    ['exec', '执行'],
    ['Port mapping', '端口映射'],
    ['Environment', '环境'],
    ['Variable', '变量'],
    ['Entry point', '入口点'],
    ['Command', '命令'],
    ['Argument', '参数'],
    ['Health check', '健康检查'],
    ['Logging', '日志'],
    ['Resource limit', '资源限制'],
    ['Memory limit', '内存限制'],
    ['CPU limit', 'CPU 限制'],
    ['User', '用户'],
    ['Group', '用户组'],
    ['Root', 'root'],
    ['Privileged', '特权模式'],
    ['Bind mount', '绑定挂载'],
    ['Tmpfs', '临时文件系统'],
    ['Docker Compose', 'Docker Compose'],
    ['Swarm', 'Swarm'],
    ['Stack', '栈'],
    ['Secret', '密钥'],
    ['Config', '配置'],
    ['Service', '服务'],
    ['Task', '任务'],
    ['Node', '节点'],
    ['Manager', '管理节点'],
    ['Worker', '工作节点'],
    ['Leader', '领导者'],
    ['Join', '加入'],
    ['Leave', '离开'],
    ['Inspect', '检查'],
    ['Stats', '统计'],
    ['Top', '进程'],
    ['Logs', '日志'],
    ['Diff', '差异'],
    ['History', '历史'],
    ['Tag', '标签'],
    ['Push', '推送'],
    ['Pull', '拉取'],
    ['Save', '保存'],
    ['Load', '加载'],
    ['Import', '导入'],
    ['Export', '导出'],
    ['Scan', '扫描'],
    ['Vulnerability', '漏洞'],
    ['Security', '安全'],
    ['Hardening', '加固'],
    ['Best practices', '最佳实践'],
    ['Production', '生产环境'],
    ['Development', '开发环境'],
    ['Staging', '预发布环境'],
    ['Debugging', '调试'],
    ['Troubleshoot', '故障排除'],
    ['Hot reload', '热重载'],
    ['Live reload', '热重载'],

    // Python
    ['Python', 'Python'],
    ['PEP 8', 'PEP 8'],
    ['Style Guide', '风格指南'],
    ['Linter', '代码检查工具'],
    ['Formatter', '格式化工具'],
    ['Virtual Environment', '虚拟环境'],
    ['venv', '虚拟环境'],
    ['Package', '包'],
    ['package', '包'],
    ['Packages', '包'],
    ['Dependency', '依赖'],
    ['dependency', '依赖'],
    ['Dependencies', '依赖'],
    ['Import', '导入'],
    ['import', '导入'],
    ['Module', '模块'],
    ['module', '模块'],
    ['pip', 'pip'],
    ['uv', 'uv'],
    ['Poetry', 'Poetry'],
    ['Function', '函数'],
    ['function', '函数'],
    ['Class', '类'],
    ['class', '类'],
    ['Method', '方法'],
    ['method', '方法'],
    ['Decorator', '装饰器'],
    ['decorator', '装饰器'],
    ['Exception', '异常'],
    ['exception', '异常'],
    ['Error', '错误'],
    ['error', '错误'],
    ['Raise', '抛出'],
    ['Catch', '捕获'],
    ['Type Hint', '类型提示'],
    ['Annotation', '注解'],
    ['Docstring', '文档字符串'],
    ['Test', '测试'],
    ['test', '测试'],
    ['Unit Test', '单元测试'],
    ['Test Case', '测试用例'],
    ['Assertion', '断言'],
    ['Mock', '模拟'],
    ['Stub', '桩'],
    ['Spy', '监视'],
    ['Fixture', '夹具'],
    ['Setup', '设置'],
    ['Teardown', '拆卸'],
    ['pytest', 'pytest'],
    ['Unittest', 'Unittest'],
    ['Coverage', '覆盖率'],
    ['Istanbul', 'Istanbul'],
    ['venv', 'venv'],
    ['Script', '脚本'],
    ['Scripting', '脚本'],
    ['Interpreter', '解释器'],
    ['Compile', '编译'],
    ['Runtime', '运行时'],
    ['Bytecode', '字节码'],
    ['Standard library', '标准库'],
    ['Third-party', '第三方'],
    ['Built-in', '内置'],
    ['List', '列表'],
    ['Dict', '字典'],
    ['Tuple', '元组'],
    ['Set', '集合'],
    ['String', '字符串'],
    ['Integer', '整数'],
    ['Float', '浮点数'],
    ['Boolean', '布尔值'],
    ['None', '空值'],
    ['Object', '对象'],
    ['Class variable', '类变量'],
    ['Instance variable', '实例变量'],
    ['Property', '属性'],
    ['Attribute', '属性'],
    ['Iterator', '迭代器'],
    ['Generator', '生成器'],
    ['Context manager', '上下文管理器'],
    ['With', 'with'],
    ['Async', '异步'],
    ['Await', '等待'],
    ['Coroutine', '协程'],
    ['Thread', '线程'],
    ['Multiprocessing', '多进程'],
    ['Queue', '队列'],
    ['Pool', '池'],
    ['Lock', '锁'],
    ['Semaphore', '信号量'],
    ['Event', '事件'],
    ['Condition', '条件'],
    ['Future', 'Future'],
    ['Lru_cache', '缓存'],
    ['Memoization', '记忆化'],
    ['Decorator', '装饰器'],
    ['Wrapper', '包装器'],
    ['Partial', '偏函数'],
    ['Compose', '组合'],
    ['Pipeline', '管道'],
    ['Decorator', '装饰器'],
    ['Context', '上下文'],
    ['Manager', '管理器'],
    ['Proxy', '代理'],
    ['Singleton', '单例'],
    ['Factory', '工厂'],
    ['Builder', '建造者'],
    ['Strategy', '策略'],
    ['Observer', '观察者'],
    ['Command', '命令'],
    ['State', '状态'],
    ['Template', '模板'],
    ['Visitor', '访问者'],
    ['Adapter', '适配器'],
    ['Facade', '门面'],
    ['Composite', '组合'],
    ['Bridge', '桥接'],
    ['Flyweight', '享元'],
    ['Proxy', '代理'],
    ['Chain of responsibility', '责任链'],
    ['Memento', '备忘录'],
    ['Mediator', '中介者'],

    // JavaScript/TypeScript
    ['JavaScript', 'JavaScript'],
    ['TypeScript', 'TypeScript'],
    ['React', 'React'],
    ['Vue', 'Vue'],
    ['Next.js', 'Next.js'],
    ['NextJS', 'NextJS'],
    ['Nuxt', 'Nuxt'],
    ['Node.js', 'Node.js'],
    ['npm', 'npm'],
    ['yarn', 'yarn'],
    ['pnpm', 'pnpm'],
    ['bun', 'bun'],
    ['Deno', 'Deno'],
    ['Component', '组件'],
    ['component', '组件'],
    ['Hook', '钩子'],
    ['hook', '钩子'],
    ['useState', 'useState'],
    ['useEffect', 'useEffect'],
    ['useCallback', 'useCallback'],
    ['useMemo', 'useMemo'],
    ['useRef', 'useRef'],
    ['useContext', 'useContext'],
    ['useReducer', 'useReducer'],
    ['useSelector', 'useSelector'],
    ['useDispatch', 'useDispatch'],
    ['State', '状态'],
    ['state', '状态'],
    ['Props', '属性'],
    ['props', '属性'],
    ['Event', '事件'],
    ['event', '事件'],
    ['Callback', '回调'],
    ['callback', '回调'],
    ['Promise', 'Promise'],
    ['promise', 'promise'],
    ['Async', '异步'],
    ['await', 'await'],
    ['Async/await', '异步/等待'],
    ['Fetch', '获取'],
    ['fetch', 'fetch'],
    ['API', 'API'],
    ['api', 'api'],
    ['REST', 'REST'],
    ['RESTful', 'RESTful'],
    ['GraphQL', 'GraphQL'],
    ['gRPC', 'gRPC'],
    ['WebSocket', 'WebSocket'],
    ['Server', '服务器'],
    ['server', '服务器'],
    ['Client', '客户端'],
    ['client', '客户端'],
    ['SSR', 'SSR'],
    ['SSG', 'SSG'],
    ['ISR', 'ISR'],
    ['SPA', 'SPA'],
    ['MPA', 'MPA'],
    ['Routing', '路由'],
    ['router', '路由'],
    ['Route', '路由'],
    ['Link', '链接'],
    ['Navigation', '导航'],
    ['Redirect', '重定向'],
    ['Middleware', '中间件'],
    ['Plugin', '插件'],
    ['plugin', '插件'],
    ['Extension', '扩展'],
    ['Module', '模块'],
    ['module', '模块'],
    ['Import', '导入'],
    ['import', '导入'],
    ['Export', '导出'],
    ['export', '导出'],
    ['Default export', '默认导出'],
    ['Named export', '命名导出'],
    ['Namespace', '命名空间'],
    ['Interface', '接口'],
    ['interface', '接口'],
    ['Type', '类型'],
    ['type', '类型'],
    ['Enum', '枚举'],
    ['enum', '枚举'],
    ['Generic', '泛型'],
    ['generic', '泛型'],
    ['Utility types', '工具类型'],
    ['Union', '联合类型'],
    ['Intersection', '交叉类型'],
    ['Literal', '字面量类型'],
    ['Optional', '可选'],
    ['optional', '可选'],
    ['Required', '必需'],
    ['required', '必需'],
    ['Readonly', '只读'],
    ['readonly', 'readonly'],
    ['Partial', '部分'],
    ['Pick', '选取'],
    ['Omit', '省略'],
    ['Record', '记录'],
    ['Map', '映射'],
    ['Set', '集合'],
    ['Array', '数组'],
    ['Tuple', '元组'],
    ['Object', '对象'],
    ['Function', '函数'],
    ['void', 'void'],
    ['never', 'never'],
    ['unknown', 'unknown'],
    ['any', 'any'],
    ['as', 'as'],
    ['instanceof', 'instanceof'],
    ['typeof', 'typeof'],
    ['keyof', 'keyof'],
    ['in', 'in'],
    ['extends', 'extends'],
    ['infer', '推断'],
    ['Library', '库'],
    ['Framework', '框架'],
    ['Runtime', '运行时'],
    ['Bundler', '打包工具'],
    ['Webpack', 'Webpack'],
    ['Vite', 'Vite'],
    ['esbuild', 'esbuild'],
    ['Rollup', 'Rollup'],
    ['Parcel', 'Parcel'],
    ['Build', '构建'],
    ['build', '构建'],
    ['Dev', '开发'],
    ['dev', '开发'],
    ['Development', '开发'],
    ['Production', '生产'],
    ['Hot Module Replacement', '模块热替换'],
    ['Tree shaking', '摇树'],
    ['Code splitting', '代码分割'],
    ['Lazy loading', '懒加载'],
    ['Prefetch', '预取'],
    ['Preload', '预加载'],
    ['Cache', '缓存'],
    ['Cache busting', '缓存破坏'],
    ['Bundle', '包'],
    ['Chunk', '块'],
    ['Entry point', '入口点'],
    ['Output', '输出'],
    ['Source map', '源码映射'],
    ['Minify', '压缩'],
    ['Uglify', '混淆'],
    ['Compress', '压缩'],
    ['Transpile', '转译'],
    ['Polyfill', 'Polyfill'],
    ['Shim', '垫片'],
    ['Compiler', '编译器'],
    ['Linter', '检查工具'],
    ['ESLint', 'ESLint'],
    ['Prettier', 'Prettier'],
    ['StyleLint', 'StyleLint'],
    ['Husky', 'Husky'],
    ['Lint-staged', 'Lint-staged'],
    ['Test', '测试'],
    ['Jest', 'Jest'],
    ['Vitest', 'Vitest'],
    ['Mocha', 'Mocha'],
    ['Chai', 'Chai'],
    ['Cypress', 'Cypress'],
    ['Playwright', 'Playwright'],
    ['Puppeteer', 'Puppeteer'],
    ['Selenium', 'Selenium'],
    ['RTL', 'RTL'],
    ['JSDOM', 'JSDOM'],
    ['Snapshot', '快照'],
    ['Mock', '模拟'],
    ['Spy', '监视'],
    ['Stub', '桩'],
    ['Fake', '伪造'],
    ['Dummy', '虚拟'],
    ['Assertion', '断言'],
    ['Expect', '期望'],
    ['Should', '应该'],
    ['Assert', '断言'],
    ['Describe', '描述'],
    ['Context', '上下文'],
    ['It', '它'],
    ['Test case', '测试用例'],
    ['Test suite', '测试套件'],
    ['Coverage', '覆盖率'],
    ['Unit test', '单元测试'],
    ['Integration test', '集成测试'],
    ['E2E test', '端到端测试'],
    ['Smoke test', '冒烟测试'],
    ['Sanity test', '健全测试'],
    ['Regression test', '回归测试'],
    ['Acceptance test', '验收测试'],
    ['Black box', '黑盒'],
    ['White box', '白盒'],
    ['Gray box', '灰盒'],
    ['Frontend', '前端'],
    ['backend', '后端'],
    ['Fullstack', '全栈'],
    ['Monorepo', 'Monorepo'],
    ['Workspace', '工作空间'],
    ['Package manager', '包管理器'],
    ['Version', '版本'],
    ['Semver', '语义化版本'],
    ['Breaking change', '破坏性变更'],
    ['Changelog', '更新日志'],
    ['Deprecation', '弃用'],
    ['Migration', '迁移'],
    ['Upgrade', '升级'],
    ['Downgrade', '降级'],
    ['Update', '更新'],
    ['Patch', '补丁'],
    ['Release', '发布'],
    ['Tag', '标签'],
    ['Branch', '分支'],
    ['Master', '主分支'],
    ['Main', '主分支'],
    ['Develop', '开发分支'],
    ['Feature branch', '功能分支'],
    ['Hotfix', '热修复'],
    ['Pull request', '拉取请求'],
    ['Code review', '代码审查'],
    ['CI/CD', 'CI/CD'],
    ['Pipeline', '流水线'],
    ['Workflow', '工作流'],
    ['Action', '操作'],
    ['Trigger', '触发器'],
    ['Job', '任务'],
    ['Step', '步骤'],
    ['Runner', '运行器'],
    ['Artifact', '制品'],
    ['Cache', '缓存'],
    ['Environment', '环境'],
    ['Secret', '密钥'],
    ['Variable', '变量'],
    ['Deploy', '部署'],
    ['deploy', '部署'],
    ['Rollback', '回滚'],
    ['Hosting', '托管'],
    ['Static', '静态'],
    ['Dynamic', '动态'],
    ['Serverless', '无服务器'],
    ['Edge', '边缘'],
    ['CDN', 'CDN'],
    ['Domain', '域名'],
    ['DNS', 'DNS'],
    ['SSL', 'SSL'],
    ['TLS', 'TLS'],
    ['HTTPS', 'HTTPS'],
    ['Certificate', '证书'],
    ['Proxy', '代理'],
    ['Gateway', '网关'],
    ['Load balancer', '负载均衡'],
    ['Reverse proxy', '反向代理'],
    ['Nginx', 'Nginx'],
    ['Apache', 'Apache'],
    ['Caddy', 'Caddy'],
    ['CORS', '跨域'],
    ['CSP', 'CSP'],
    ['XSS', 'XSS'],
    ['CSRF', 'CSRF'],
    ['SQL injection', 'SQL 注入'],
    ['Sanitize', '净化'],
    ['Escape', '转义'],
    ['Encode', '编码'],
    ['Decode', '解码'],
    ['Encrypt', '加密'],
    ['Decrypt', '解密'],
    ['Hash', '哈希'],
    ['Salt', '盐'],
    ['Token', '令牌'],
    ['JWT', 'JWT'],
    ['OAuth', 'OAuth'],
    ['SAML', 'SAML'],
    ['SSO', '单点登录'],
    ['MFA', '多因素认证'],
    ['2FA', '双因素认证'],
    ['Password', '密码'],
    ['Authentication', '认证'],
    ['Authorization', '授权'],
    ['Permission', '权限'],
    ['RBAC', '基于角色的访问控制'],
    ['Policy', '策略'],
    ['Role', '角色'],
    ['User', '用户'],
    ['Admin', '管理员'],
    ['Root', 'root'],
    ['Session', '会话'],
    ['Cookie', 'Cookie'],
    ['Header', '请求头'],
    ['Body', '请求体'],
    ['Request', '请求'],
    ['Response', '响应'],
    ['Status code', '状态码'],
    ['Method', '方法'],
    ['GET', 'GET'],
    ['POST', 'POST'],
    ['PUT', 'PUT'],
    ['PATCH', 'PATCH'],
    ['DELETE', 'DELETE'],
    ['OPTIONS', 'OPTIONS'],
    ['HEAD', 'HEAD'],
    ['Query string', '查询字符串'],
    ['URL', 'URL'],
    ['Path', '路径'],
    ['Route', '路由'],
    ['Endpoint', '端点'],
    ['Pagination', '分页'],
    ['Cursor', '游标'],
    ['Offset', '偏移'],
    ['Limit', '限制'],
    ['Filter', '过滤'],
    ['Sort', '排序'],
    ['Search', '搜索'],
    ['Aggregate', '聚合'],
    ['Batch', '批量'],
    ['Webhook', 'Webhook'],
    ['Event', '事件'],
    ['Stream', '流'],
    ['Upload', '上传'],
    ['Download', '下载'],
    ['File', '文件'],
    ['Multipart', '多部分'],
    ['Form data', '表单数据'],
    ['JSON', 'JSON'],
    ['XML', 'XML'],
    ['YAML', 'YAML'],
    ['TOML', 'TOML'],
    ['SDK', 'SDK'],
    ['Client library', '客户端库'],
    ['CLI', 'CLI'],
    ['Command line', '命令行'],
    ['Terminal', '终端'],
    ['Shell', 'Shell'],
    ['Script', '脚本'],
    ['Bash', 'Bash'],
    ['Zsh', 'Zsh'],
    ['Fish', 'Fish'],
    ['PowerShell', 'PowerShell'],
    ['SSH', 'SSH'],
    ['SCP', 'SCP'],
    ['SFTP', 'SFTP'],
    ['rsync', 'rsync'],
    ['curl', 'curl'],
    ['wget', 'wget'],
    ['ping', 'ping'],
    ['netstat', 'netstat'],
    ['ss', 'ss'],
    ['ip', 'ip'],
    ['ifconfig', 'ifconfig'],
    ['dig', 'dig'],
    ['nslookup', 'nslookup'],
    ['host', 'host'],
    ['Packet', '数据包'],
    ['Port', '端口'],
    ['Bind', '绑定'],
    ['Listen', '监听'],
    ['Connect', '连接'],
    ['Accept', '接受'],
    ['Send', '发送'],
    ['Receive', '接收'],
    ['Socket', '套接字'],
    ['Connection', '连接'],
    ['Protocol', '协议'],
    ['TCP', 'TCP'],
    ['UDP', 'UDP'],
    ['HTTP', 'HTTP'],
    ['HTTPS', 'HTTPS'],
    ['WebSocket', 'WebSocket'],
    ['FTP', 'FTP'],
    ['SMTP', 'SMTP'],
    ['IMAP', 'IMAP'],
    ['POP3', 'POP3'],
    ['DNS', 'DNS'],
    ['DHCP', 'DHCP'],
    ['NTP', 'NTP'],
    ['SNMP', 'SNMP'],
    ['LDAP', 'LDAP'],
    ['Kerberos', 'Kerberos'],
    ['SSH', 'SSH'],
    ['VPN', 'VPN'],
    ['NAT', 'NAT'],
    ['Firewall', '防火墙'],
    ['Router', '路由器'],
    ['Switch', '交换机'],
    ['Gateway', '网关'],
    ['Subnet', '子网'],
    ['CIDR', 'CIDR'],
    ['VLAN', 'VLAN'],
    ['VPN', 'VPN'],
    ['Tunnel', '隧道'],
    ['Proxy', '代理'],
    ['NAT', 'NAT'],
    ['Routing', '路由'],
    ['Switching', '交换'],
    ['Multiplexing', '复用'],
    ['Fragmentation', '分片'],
    ['Encryption', '加密'],
    ['Decryption', '解密'],
    ['Encoding', '编码'],
    ['Decoding', '解码'],
    ['Serialization', '序列化'],
    ['Deserialization', '反序列化'],
    ['Parse', '解析'],
    ['Stringify', '字符串化'],
    ['Validate', '验证'],
    ['Sanitize', '净化'],
    ['Escape', '转义'],
    ['Unescape', '反转义'],
    ['HTML entity', 'HTML 实体'],
    ['URL encode', 'URL 编码'],
    ['Base64', 'Base64'],
    ['UTF-8', 'UTF-8'],
    ['ASCII', 'ASCII'],
    ['Unicode', 'Unicode'],
    ['Regex', '正则表达式'],
    ['Pattern', '模式'],
    ['Match', '匹配'],
    ['Replace', '替换'],
    ['Extract', '提取'],
    ['Test', '测试'],
    ['Global', '全局'],
    ['Local', '本地'],
    ['Case sensitive', '大小写敏感'],
    ['Case insensitive', '大小写不敏感'],
    ['Greedy', '贪婪'],
    ['Lazy', '懒惰'],
    ['Capture group', '捕获组'],
    ['Named group', '命名组'],
    ['Lookahead', '前瞻'],
    ['Lookbehind', '后顾'],
    ['Anchor', '锚点'],
    ['Quantifier', '量词'],
    ['Alternation', '选择'],
    ['Character class', '字符类'],
    ['Metacharacter', '元字符'],
    ['Escape sequence', '转义序列'],
    ['Wildcard', '通配符'],
    ['Compression', '压缩'],
    ['Archive', '归档'],
    ['tar', 'tar'],
    ['gzip', 'gzip'],
    ['zip', 'zip'],
    ['unzip', 'unzip'],
    ['7z', '7z'],
    ['rar', 'rar'],
    ['bz2', 'bz2'],
    ['xz', 'xz'],
    ['zstd', 'zstd'],
    ['Process', '进程'],
    ['Thread', '线程'],
    ['Child process', '子进程'],
    ['Parent process', '父进程'],
    ['Zombie', '僵尸进程'],
    ['Orphan', '孤儿进程'],
    ['Daemon', '守护进程'],
    ['Fork', '分叉'],
    ['Exec', '执行'],
    ['Spawn', '生成'],
    ['Kill', '终止'],
    ['Signal', '信号'],
    ['IPC', '进程间通信'],
    ['Pipe', '管道'],
    ['FIFO', 'FIFO'],
    ['Message queue', '消息队列'],
    ['Shared memory', '共享内存'],
    ['Semaphore', '信号量'],
    ['Socket', '套接字'],
    ['Memory', '内存'],
    ['Heap', '堆'],
    ['Stack', '栈'],
    ['Garbage collection', '垃圾回收'],
    ['GC', 'GC'],
    ['Allocation', '分配'],
    ['Deallocation', '释放'],
    ['Leak', '泄漏'],
    ['Buffer', '缓冲区'],
    ['Overflow', '溢出'],
    ['Underflow', '下溢'],
    ['Pointer', '指针'],
    ['Reference', '引用'],
    ['Copy', '复制'],
    ['Move', '移动'],
    ['Clone', '克隆'],
    ['Deep copy', '深拷贝'],
    ['Shallow copy', '浅拷贝'],
    ['Serialize', '序列化'],
    ['Deserialize', '反序列化'],
    ['Marshal', '编组'],
    ['Unmarshal', '解组'],
    ['Encode', '编码'],
    ['Decode', '解码'],
    ['Transcode', '转码'],
    ['Stream', '流'],
    ['Buffer', '缓冲'],
    ['Flush', '刷新'],
    ['EOF', 'EOF'],
    ['File descriptor', '文件描述符'],
    ['Handle', '句柄'],
    ['Lock', '锁'],
    ['Mutex', '互斥锁'],
    ['Semaphore', '信号量'],
    ['Monitor', '监视器'],
    ['Condition', '条件变量'],
    ['Deadlock', '死锁'],
    ['Race condition', '竞态条件'],
    ['Atomic', '原子操作'],
    ['Synchronize', '同步'],
    ['Async', '异步'],
    ['Await', '等待'],
    ['Callback', '回调'],
    ['Promise', 'Promise'],
    ['Future', 'Future'],
    ['Generator', '生成器'],
    ['Iterator', '迭代器'],
    ['Coroutine', '协程'],
    ['Channel', '通道'],
    ['Goroutine', 'Goroutine'],
    ['Actor', '参与者'],
    ['Message passing', '消息传递'],
    ['Event loop', '事件循环'],
    ['Event driven', '事件驱动'],
    ['Observer', '观察者'],
    ['Pub/Sub', '发布/订阅'],
    ['Listener', '监听器'],
    ['Handler', '处理器'],
    ['Callback', '回调'],
    ['Middleware', '中间件'],
    ['Interceptor', '拦截器'],
    ['Decorator', '装饰器'],
    ['Wrapper', '包装器'],
    ['Adapter', '适配器'],
    ['Facade', '门面'],
    ['Proxy', '代理'],
    ['Bridge', '桥接'],
    ['Strategy', '策略'],
    ['Policy', '策略'],
    ['Template method', '模板方法'],
    ['Command', '命令'],
    ['Memento', '备忘录'],
    ['State', '状态'],
    ['Visitor', '访问者'],
    ['Interpreter', '解释器'],
    ['Composite', '组合'],
    ['Flyweight', '享元'],
    ['Chain of responsibility', '责任链'],
    ['Object pool', '对象池'],
    ['Prototype', '原型'],
    ['Factory', '工厂'],
    ['Abstract factory', '抽象工厂'],
    ['Builder', '建造者'],
    ['Singleton', '单例'],
    ['Dependency injection', '依赖注入'],
    ['Inversion of control', '控制反转'],
    ['Service locator', '服务定位器'],
    ['Registry', '注册表'],
    ['Repository', '仓储'],
    ['DAO', 'DAO'],
    ['DTO', 'DTO'],
    ['Entity', '实体'],
    ['Value object', '值对象'],
    ['Aggregate', '聚合'],
    ['Aggregate root', '聚合根'],
    ['Factory', '工厂'],
    ['Service', '服务'],
    ['Application service', '应用服务'],
    ['Domain service', '领域服务'],
    ['Infrastructure service', '基础设施服务'],
    ['Domain event', '领域事件'],
    ['Event sourcing', '事件溯源'],
    ['CQRS', 'CQRS'],
    ['Event-driven architecture', '事件驱动架构'],
    ['Microservices', '微服务'],
    ['Monolith', '单体应用'],
    ['Service mesh', '服务网格'],
    ['API gateway', 'API 网关'],
    ['Load balancer', '负载均衡'],
    ['Circuit breaker', '断路器'],
    ['Rate limiter', '限流器'],
    ['Retry', '重试'],
    ['Timeout', '超时'],
    ['Bulkhead', '隔板'],
    ['Dead letter queue', '死信队列'],
    ['Message broker', '消息代理'],
    ['Kafka', 'Kafka'],
    ['RabbitMQ', 'RabbitMQ'],
    ['Redis', 'Redis'],
    ['MongoDB', 'MongoDB'],
    ['PostgreSQL', 'PostgreSQL'],
    ['MySQL', 'MySQL'],
    ['MariaDB', 'MariaDB'],
    ['SQLite', 'SQLite'],
    ['Oracle', 'Oracle'],
    ['SQL Server', 'SQL Server'],
    ['DynamoDB', 'DynamoDB'],
    ['Cassandra', 'Cassandra'],
    ['Couchbase', 'Couchbase'],
    ['Neo4j', 'Neo4j'],
    ['ArangoDB', 'ArangoDB'],
    ['InfluxDB', 'InfluxDB'],
    ['TimescaleDB', 'TimescaleDB'],
    ['ClickHouse', 'ClickHouse'],
    ['BigQuery', 'BigQuery'],
    ['Snowflake', 'Snowflake'],
    ['Redshift', 'Redshift'],
    ['Athena', 'Athena'],
    ['Presto', 'Presto'],
    ['Trino', 'Trino'],
    ['Spark', 'Spark'],
    ['Hadoop', 'Hadoop'],
    ['Hive', 'Hive'],
    ['HBase', 'HBase'],
    ['Flink', 'Flink'],
    ['Storm', 'Storm'],
    ['Kafka Streams', 'Kafka Streams'],
    ['Elasticsearch', 'Elasticsearch'],
    ['Logstash', 'Logstash'],
    ['Kibana', 'Kibana'],
    ['Grafana', 'Grafana'],
    ['Prometheus', 'Prometheus'],
    ['Alertmanager', 'Alertmanager'],
    ['PagerDuty', 'PagerDuty'],
    ['Datadog', 'Datadog'],
    ['New Relic', 'New Relic'],
    ['Sentry', 'Sentry'],
    ['CloudWatch', 'CloudWatch'],
    ['CloudTrail', 'CloudTrail'],
    ['X-Ray', 'X-Ray'],
    ['APM', 'APM'],
    ['Infrastructure', '基础设施'],
    ['Compute', '计算'],
    ['Storage', '存储'],
    ['Network', '网络'],
    ['Database', '数据库'],
    ['Cache', '缓存'],
    ['Queue', '队列'],
    ['Search', '搜索'],
    ['Analytics', '分析'],
    ['ML', '机器学习'],
    ['AI', 'AI'],
    ['Lambda', 'Lambda'],
    ['Serverless', '无服务器'],
    ['Function', '函数'],
    ['Container', '容器'],
    ['Orchestration', '编排'],
    ['Kubernetes', 'Kubernetes'],
    ['K8s', 'K8s'],
    ['Docker', 'Docker'],
    ['Pod', 'Pod'],
    ['Service', '服务'],
    ['Deployment', '部署'],
    ['ReplicaSet', '副本集'],
    ['StatefulSet', '有状态副本集'],
    ['DaemonSet', '守护进程集'],
    ['Job', '任务'],
    ['CronJob', '定时任务'],
    ['ConfigMap', 'ConfigMap'],
    ['Secret', 'Secret'],
    ['Ingress', 'Ingress'],
    ['NetworkPolicy', '网络策略'],
    ['ServiceAccount', '服务账号'],
    ['RBAC', 'RBAC'],
    ['PVC', 'PVC'],
    ['PV', '持久卷'],
    ['StorageClass', '存储类'],
    ['Namespace', '命名空间'],
    ['Node', '节点'],
    ['Cluster', '集群'],
    ['Master', '主节点'],
    ['Worker', '工作节点'],
    ['Control plane', '控制平面'],
    ['Data plane', '数据平面'],
    ['Etcd', 'Etcd'],
    ['API server', 'API 服务器'],
    ['Scheduler', '调度器'],
    ['Controller', '控制器'],
    ['Kubelet', 'Kubelet'],
    ['Kube-proxy', 'Kube-proxy'],
    ['CNI', 'CNI'],
    ['CSI', 'CSI'],
    ['CRI', 'CRI'],
    ['Helm', 'Helm'],
    ['Chart', 'Chart'],
    ['Values', 'Values'],
    ['Template', '模板'],
    ['Release', '发布'],
    ['ArgoCD', 'ArgoCD'],
    ['Flux', 'Flux'],
    ['Kustomize', 'Kustomize'],
    ['K9s', 'K9s'],
    ['Lens', 'Lens'],
    ['Rancher', 'Rancher'],
    ['OpenShift', 'OpenShift'],
    ['Anthos', 'Anthos'],
    ['EKS', 'EKS'],
    ['AKS', 'AKS'],
    ['GKE', 'GKE'],
    ['AAD', 'AAD'],
    ['IAM', 'IAM'],
    ['VPC', 'VPC'],
    ['Subnet', '子网'],
    ['Security group', '安全组'],
    ['NACL', 'NACL'],
    ['Route table', '路由表'],
    ['Internet gateway', '互联网网关'],
    ['NAT gateway', 'NAT 网关'],
    ['VPN gateway', 'VPN 网关'],
    ['Direct Connect', '直连'],
    ['CloudFront', 'CloudFront'],
    ['Route 53', 'Route 53'],
    ['S3', 'S3'],
    ['EBS', 'EBS'],
    ['EFS', 'EFS'],
    ['FSx', 'FSx'],
    ['SQS', 'SQS'],
    ['SNS', 'SNS'],
    ['EventBridge', 'EventBridge'],
    ['Step Functions', 'Step Functions'],
    ['Kinesis', 'Kinesis'],
    ['DynamoDB', 'DynamoDB'],
    ['RDS', 'RDS'],
    ['Aurora', 'Aurora'],
    ['ElastiCache', 'ElastiCache'],
    ['MemoryDB', 'MemoryDB'],
    ['DocumentDB', 'DocumentDB'],
    ['Neptune', 'Neptune'],
    ['QLDB', 'QLDB'],
    ['Timestream', 'Timestream'],
    ['Glue', 'Glue'],
    ['Lake Formation', 'Lake Formation'],
    ['MSK', 'MSK'],
    ['MQ', 'MQ'],
    ['Redshift', 'Redshift'],
    ['EMR', 'EMR'],
    ['SageMaker', 'SageMaker'],
    ['Comprehend', 'Comprehend'],
    ['Rekognition', 'Rekognition'],
    ['Polly', 'Polly'],
    ['Transcribe', 'Transcribe'],
    ['Translate', 'Translate'],
    ['Lex', 'Lex'],
    ['Connect', 'Connect'],
    ['Pinpoint', 'Pinpoint'],
    ['SES', 'SES'],
    ['SQS', 'SQS'],
    ['Batch', 'Batch'],
    ['ECS', 'ECS'],
    ['Fargate', 'Fargate'],
    ['ECR', 'ECR'],
    ['CodeBuild', 'CodeBuild'],
    ['CodeDeploy', 'CodeDeploy'],
    ['CodePipeline', 'CodePipeline'],
    ['CodeCommit', 'CodeCommit'],
    ['CodeArtifact', 'CodeArtifact'],
    ['CloudFormation', 'CloudFormation'],
    ['CDK', 'CDK'],
    ['Terraform', 'Terraform'],
    ['Pulumi', 'Pulumi'],
    ['Ansible', 'Ansible'],
    ['Chef', 'Chef'],
    ['Puppet', 'Puppet'],
    ['Vagrant', 'Vagrant'],
    ['Packer', 'Packer'],
    ['Vault', 'Vault'],
    ['Consul', 'Consul'],
    ['Nomad', 'Nomad'],
    ['Traefik', 'Traefik'],
    ['Envoy', 'Envoy'],
    ['Istio', 'Istio'],
    ['Linkerd', 'Linkerd'],
    ['Kuma', 'Kuma'],
    ['Cilium', 'Cilium'],
    ['Calico', 'Calico'],
    ['Flannel', 'Flannel'],
    ['Weave', 'Weave'],
    ['Harbor', 'Harbor'],
    [' Quay', 'Quay'],
    ['Artifactory', 'Artifactory'],
    ['Nexus', 'Nexus'],
    ['Sonatype', 'Sonatype'],
    ['JFrog', 'JFrog'],
    ['Datree', 'Datree'],
    ['Polaris', 'Polaris'],
    ['Fairwinds', 'Fairwinds'],
    ['Snyk', 'Snyk'],
    ['Trivy', 'Trivy'],
    ['Falco', 'Falco'],
    ['Aqua', 'Aqua'],
    ['Sysdig', 'Sysdig'],
    ['Cortex', 'Cortex'],
    ['Thanos', 'Thanos'],
    ['VictoriaMetrics', 'VictoriaMetrics'],
    ['Mimir', 'Mimir'],
    ['Tempo', 'Tempo'],
    ['Loki', 'Loki'],
    ['Alertmanager', 'Alertmanager'],
    ['Pushgateway', 'Pushgateway'],
    ['Node exporter', 'Node exporter'],
    ['Blackbox exporter', 'Blackbox exporter'],
    ['Consul exporter', 'Consul exporter'],
    ['HAProxy', 'HAProxy'],
    ['Keepalived', 'Keepalived'],
    ['Pacemaker', 'Pacemaker'],
    ['Corosync', 'Corosync'],
    ['DRBD', 'DRBD'],
    ['GlusterFS', 'GlusterFS'],
    ['Ceph', 'Ceph'],
    ['Longhorn', 'Longhorn'],
    ['Rook', 'Rook'],
    ['OpenEBS', 'OpenEBS'],
    ['StorageOS', 'StorageOS'],
    ['Portworx', 'Portworx'],
    ['Velero', 'Velero'],
    ['Restic', 'Restic'],
    ['Kopia', 'Kopia'],
    ['Duplicati', 'Duplicati'],
    ['BorgBackup', 'BorgBackup'],
    ['Rsync', 'Rsync'],
    ['Rclone', 'Rclone'],
    ['Duplicacy', 'Duplicacy'],
    ['Burp', 'Burp'],
    ['OWASP', 'OWASP'],
    ['ZAP', 'ZAP'],
    ['Nikto', 'Nikto'],
    ['Nmap', 'Nmap'],
    ['Metasploit', 'Metasploit'],
    ['Burp Suite', 'Burp Suite'],
    ['SQLMap', 'SQLMap'],
    ['Hydra', 'Hydra'],
    ['John', 'John'],
    ['Hashcat', 'Hashcat'],
    ['Aircrack-ng', 'Aircrack-ng'],
    ['Wireshark', 'Wireshark'],
    ['Tcpdump', 'Tcpdump'],
    ['Scapy', 'Scapy'],
    ['Netcat', 'Netcat'],
    ['Socat', 'Socat'],
    ['Ngrep', 'Ngrep'],
    ['Dsniff', 'Dsniff'],
    ['Ettercap', 'Ettercap'],
    ['Bettercap', 'Bettercap'],
    ['Responder', 'Responder'],
    ['Impacket', 'Impacket'],
    ['BloodHound', 'BloodHound'],
    ['Mimikatz', 'Mimikatz'],
    ['PowerSploit', 'PowerSploit'],
    ['Empire', 'Empire'],
    ['Cobalt Strike', 'Cobalt Strike'],
    ['Metasploit', 'Metasploit'],
    ['SET', 'SET'],
    ['Fast-Track', 'Fast-Track'],
    ['MFASweep', 'MFASweep'],
    ['Lake', '湖'],
    ['Warehouse', '数据仓库'],
    ['Data lake', '数据湖'],
    ['Data warehouse', '数据仓库'],
    ['Data mart', '数据集市'],
    ['Data mesh', '数据网格'],
    ['Data lakehouse', '湖仓一体'],
    ['ETL', 'ETL'],
    ['ELT', 'ELT'],
    ['CDC', 'CDC'],
    ['Data integration', '数据集成'],
    ['Data pipeline', '数据管道'],
    ['Stream processing', '流处理'],
    ['Batch processing', '批处理'],
    ['Real-time', '实时'],
    ['Near real-time', '近实时'],
    ['Complex event processing', '复杂事件处理'],
    ['Window', '窗口'],
    ['Tumbling window', '滚动窗口'],
    ['Sliding window', '滑动窗口'],
    ['Session window', '会话窗口'],
    ['Counting window', '计数窗口'],
    ['Time window', '时间窗口'],
    ['Watermark', '水位线'],
    ['Checkpoint', '检查点'],
    ['State', '状态'],
    ['Stateful', '有状态'],
    ['Stateless', '无状态'],
    ['Exactly-once', '恰好一次'],
    ['At-least-once', '至少一次'],
    ['At-most-once', '最多一次'],
    ['Backpressure', '背压'],
    ['Buffer', '缓冲区'],
    ['Throughput', '吞吐量'],
    ['Latency', '延迟'],
    ['Concurrency', '并发'],
    ['Parallelism', '并行'],
    ['Partition', '分区'],
    ['Shard', '分片'],
    ['Replica', '副本'],
    ['Leader', '领导者'],
    ['Follower', '跟随者'],
    ['Learner', '学习者'],
    ['Candidate', '候选者'],
    ['Coordinator', '协调者'],
    ['Partition leader', '分区领导者'],
    ['Partition replica', '分区副本'],
    ['Consensus', '共识'],
    ['Raft', 'Raft'],
    ['Paxos', 'Paxos'],
    ['2PC', '两阶段提交'],
    ['3PC', '三阶段提交'],
    ['Saga', 'Saga'],
    ['Outbox', '发件箱模式'],
    ['Change data capture', '变更数据捕获'],
    ['Dual write', '双写'],
    ['Eventual consistency', '最终一致性'],
    ['Strong consistency', '强一致性'],
    ['CAP theorem', 'CAP 定理'],
    ['PACELC', 'PACELC'],
    ['ACID', 'ACID'],
    ['BASE', 'BASE'],
    ['Saga pattern', 'Saga 模式'],
    ['CQRS pattern', 'CQRS 模式'],
    ['Event sourcing pattern', '事件溯源模式'],
    ['Outbox pattern', '发件箱模式'],
    ['Retry pattern', '重试模式'],
    ['Circuit breaker pattern', '断路器模式'],
    ['Bulkhead pattern', '隔板模式'],
    ['Rate limiting pattern', '限流模式'],
    ['Backpressure pattern', '背压模式'],
    ['Timeout pattern', '超时模式'],
    ['Dead letter pattern', '死信模式'],
    ['Poison message', '毒消息'],
    ['Idempotent consumer', '幂等消费者'],
    ['Transactional outbox', '事务性发件箱'],
    ['Change data capture', '变更数据捕获'],
    ['Database replication', '数据库复制'],
    ['Multi-master', '多主'],
    ['Primary-backup', '主从'],
    ['Leader-based', '基于领导者'],
    ['Leaderless', '无领导者'],
    ['CRDT', 'CRDT'],
    ['Operational transformation', '操作转换'],
    ['Conflict-free replicated data type', '无冲突复制数据类型'],
  ]

  let result = body

  // 按长度降序排序，避免短词先匹配
  translations.sort((a, b) => b[0].length - a[0].length)

  for (const [en, zh] of translations) {
    // 使用 \b 进行单词边界匹配
    const pattern = `(?<![\\u4e00-\\u9fa5])\\b${escapeRegExp(en)}\\b(?![\\u4e00-\\u9fa5])`
    const regex = new RegExp(pattern, 'gi')
    result = result.replace(regex, zh)
  }

  return result
}

function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

// 处理单个 SKILL.md
function processSkill(skillPath, skillDir) {
  try {
    let content = fs.readFileSync(skillPath, 'utf8')
    const translated = translate(content)
    fs.writeFileSync(skillPath, translated)
    return true
  } catch (e) {
    console.error(`Error processing ${skillDir}:`, e.message)
    return false
  }
}

// 主处理
const dirs = fs.readdirSync(SKILLS_DIR).filter(f => {
  return fs.statSync(path.join(SKILLS_DIR, f)).isDirectory()
})

console.log(`Processing ${dirs.length} skills...\n`)

let processed = 0
let errors = 0

for (const dir of dirs) {
  const skillPath = path.join(SKILLS_DIR, dir, 'SKILL.md')
  if (!fs.existsSync(skillPath)) continue

  if (processSkill(skillPath, dir)) {
    processed++
    if (processed % 20 === 0) {
      console.log(`Translated ${processed}/${dirs.length}...`)
    }
  } else {
    errors++
  }
}

console.log(`\nDone: ${processed} translated, ${errors} errors`)
